### ISSUE TITLE
converting old history file.

### ISSUE THREAD

**Issue by ghost** [GilgusMaximus/FreeTube-Legacy-Converter#1]
https://github.com/FreeTubeApp/FreeTube/issues/764#issuecomment-721713083

referencing this post.

im trying to convert my old history file with the provided executables.
after some trouble i was able to get further until i hit this error:

![Screenshot from 2020-11-04 14-48-26](https://user-images.githubusercontent.com/65868299/98119374-d0ba2380-1eac-11eb-8bb6-b3d671f2b0c5.png)

i would consider myself quite the novice in such things so i am unable to see what this really means now.

**Comment by GilgusMaximus** [comment]
Hi.
So your problem seems to be that one of your paths is not a file but a directory.
If you checked that your two paths are really the files like ~/mycooldirectory/profiles.db,
I am just gonna suggest checking the following 3 things, which I have from [this](https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a) StackOverflow post.
> Three things to make sure here.
>
>Make sure the file exists. If it does not, you need to create it. (If NPM depends on any specific information in the file, you will need to have that information there).
>
>    Make sure it is in fact a file and not a directory.
>
>    It has the right permissions. You can change the file to have all permissions with "sudo chmod 777 FILE_NAME". (Careful: You are giving Read, Write and Execute permissions to every one on that file)


And in regards to your previous comment on the other issue, which I only see in my Github notifications but not actually in the issue itself for some reason, here a short explanation on what your problems were so that you can learn for the next time:

> "Aborting: Wrong number of arguments were supplied. Expected 5, got 1"

This means that you did not specify enough arguments for the program. Because this program is a command line tool without any interface or shell to provide arguments later on, you have to provide the arguments (filepath, what you want to do, etc..) when executing the program. 

So what you most likely did was along something like this: `./ft-converter-YourOS `. This however does not provide any information to the program on what data to work on. Because as it is stated in the ReadMe: 
>History
>./ft-convert -history -op /path/to/old/file/videoHistory.db -np /path/to/new/file/history.db

So here you can see, that you do the execution of the program `./ft-convert` and then provide the first argument `-history` which for this program tells the program that you want to convert your old history. `-op` tells the program that the **next** string is the path of the original history file (from the old FreeTube). So you now type in the path to that file `~/mycooldirectoy/videoHistory.db`. And then the `-np` works the same as the -op, but tells the program the next string in the console is the path to the new history file, so where the data should be written to `~/mycooldirectoyofnewfreetube/history.db`.

And then that is it. You press enter and the programs knows everything it needs to do the conversion.


Regarding your second problem with the source code 
>Error: Cannot find module 'yt-channel-info'"

means that you installed NodeJS correctly, however you did not run the instruction `npm install` from a shell inside the root directory of the source code. Because this instruction tells NPM to download all NodeJS modules this program depends on. And after that, you can run the program with the same arguments as before, but instead of `./ft-convert`you need to run `npm run index.js` in order to run it, because it is not an executable.

I hope this explanation helps you and makes things easier.
If you have any questions, feel free to reach out again

**Comment by ghost** [comment]
thank you very much i didnt know i had to create an entire new file.
while it did give me the same "error" message it still imported my history!

**Comment by GilgusMaximus** [comment]
Great that it worked for you 👍
